version: '3'
services:
  test-server:
    container_name: test-server
    restart: always
    environment:
      - V_ENV_1=valuen 1 test compose
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - ./.env
    expose:
      - 3000