version: '3'
services:
  cartas-server:
    container_name: cartas-server
    restart: always
    environment:
      - V_ENV_1=valuen 1 test compose
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - ./.env
volumes:
